AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Email sending API using Amazon SES

Resources:
  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src
      Policies:
        - AWSSecretsManagerReadWrite
        - AmazonSESFullAccess
      Environment:
        Variables:
          REGION: !Ref AWS::Region
      Events:
        SendEmail:
          Type: Api
          Properties:
            Path: /send-email
            Method: post

  EmailApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'" 